### ISSUE TITLE
NameError: name 'pathlib' is not defined

### ISSUE THREAD

**Issue by jmcharter** [mmskv/toggl_polybar#2]
Path is imported from pathlib as so:

    NameError: name 'pathlib' is not defined

but then env path is set as follows:

    env_path = Path(__file__).parent.absolute() / 'togglapi.env'

resulting  in error:

    Traceback (most recent call last):
    File "toggl.py", line 7, in <module>
    env_path = pathlib.Path(__file__).parent.absolute() / 'togglapi.env'
    NameError: name 'pathlib' is not defined

**Comment by mmskv** [comment]
Thank you

**Comment by jmcharter** [comment]
No problem, thanks for accepting the PR!
